### ISSUE TITLE
sudgestion to rename requests_template.py to *.tmpl

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#15]
Since pip thinks the file is a regular python file:

Getting distribution for 'edeposit.amqp.pdfgen'.
  File "build/bdist.linux-x86_64/egg/edeposit/amqp/pdfgen/structures/requests_template.py", line 5
    $warning_mark
    ^

**Comment by Bystroushaak** [comment]
Okay, I will rename it and release new package when I get to Klementinum.

**Comment by hopru** [comment]
Jo, prosím, Honzo, vyhoï mì z toho githubu… dik.

Jan Prùcha
prucha@webrevol.cz
+420 602 602 753



22. 1. 2015 v 11:00, Jan Stavel <notifications@github.com>:

**Comment by Bystroushaak** [comment]
Ahoj, teď jsem tě z něj vyhodil, dál už by ti to nemělo chodit.

**Comment by Bystroushaak** [comment]
Resp. budou ti chodit jen zprávy z issues, do kterých jsi něco napsal.
