### ISSUE TITLE
response of an amqp service - no rst template to generate contract agreement

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#16]
IOError: [Errno 2] No such file or directory: '/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/resources/Licencni_smlouva_o_dodavani_elektronickych_publikaci_a_jejich_uziti.rst'

**Comment by Bystroushaak** [comment]
Working on this. It looks like pip for some strange reason ignores manifest.in.

**Comment by Bystroushaak** [comment]
http://stackoverflow.com/questions/13307408/python-packaging-data-files-are-put-properly-in-tar-gz-file-but-are-not-install

**Comment by Bystroushaak** [comment]
Still working on this. It looks like the builtin help generator causes this.

**Comment by Bystroushaak** [comment]
Fixed. I've had to remove HTML documentation generator - documentation will be now only available online.
