### ISSUE TITLE
TypeError: __new__() takes at least 24 arguments (24 given)

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#21]
filename = originalfile.file and originalfile.file.filename or ""
        request = GenerateReview (
            nazev = epublication.title,
            podnazev = epublication.podnazev,
            cast = epublication.cast,
            nazev_casti = epublication.nazev_casti,
            isbn = get('isbn'),
            isbn_souboru_publikaci = epublication.isbn_souboru_publikaci,
            generated_isbn = get('generated_isbn'),
            poradi_vydani = epublication.poradi_vydani,
            rok_vydani = epublication.rok_vydani,
            vydano_v_koedici_s = epublication.vydano_v_koedici_s,
            cena = epublication.cena,
            offer_to_riv = epublication.offer_to_riv,
            category_for_riv  = epublication.category_for_riv,
            is_public = epublication.is_public,
            libraries_accessing = libraries_accessing,
            libraries_that_can_access = libraries_that_can_access,
            zpracovatel_zaznamu = get('zpracovatel_zaznamu'),
            url = get('url'),
            format = get('format'),
            filename = filename,
            author1 = autor1,
            author2 = autor2,
            author3 = autor3,
            # internal_url = originalfile.absolute_url()
        )
TypeError: __new__() takes at least 24 arguments (24 given)
> /opt/edeposit/src/edeposit.content/edeposit/content/amqp.py(637)send()
-> author3 = autor3,

**Comment by Bystroushaak** [comment]
And if you add the internal url field?

**Comment by Bystroushaak** [comment]
It works with the test JSON.

**Comment by jstavel** [comment]
it doesnot work..
hm.

**Comment by jstavel** [comment]
I do not know a reason of __new__ machinery and templates.

**Comment by Bystroushaak** [comment]
The reason is that autor1/2/3 are optional data, which may be set to ``None``. ``NamedTuple`` has to have ``__new__()`` call when you want default arguments.

**Comment by Bystroushaak** [comment]
Also there were some problems in order persistence, which required ``get_rst() / semantic_dict``.

**Comment by Bystroushaak** [comment]
It works for this JSON data:

```JSON
{  
   "nazev":"Den remesel",
   "podnazev":"informační leták",
   "cast":"prvni cast",
   "nazev_casti":"nejaky nazev casti",
   "isbn":null,
   "isbn_souboru_publikaci":null,
   "generated_isbn":true,
   "poradi_vydani":"první",
   "misto_vydani":"Zlin",
   "rok_vydani":2015,
   "nakladatel_vydavatel":"Zlínské nakladatelství",
   "vydano_v_koedici_s":null,
   "cena":null,
   "offer_to_riv":true,
   "category_for_riv":"1.        společenské, humanitní a umělecké vědy (SHVa)",
   "is_public":false,
   "libraries_accessing":"Vybrané knihovny mají přístup",
   "libraries_that_can_access":[  
      {  
         "id":"moravska-zemska-knihovna",
         "title":"Moravská Zemská knihovna"
      },
      {  
         "id":"mestska-knihovna-praha",
         "title":"Městská knihovna Praha"
      },
      {  
         "id":"narodni-knihovna-praha",
         "title":"Národní knihovna Praha"
      }
   ],
   "zpracovatel_zaznamu":"jans",
   "url":null,
   "format":"text/html",
   "filename": "story_of_mighty_azgabash.txt",
   "author1": "xex",
   "author2": "xux",
   "author3": "xax",
   "internal_url": "http://zde_bude_odkaz_do_edepositu"
}```

**Comment by Bystroushaak** [comment]
Oh. But I didn't try to send the data over AMQP, there may be the problem.

**Comment by jstavel** [comment]
TypeError: __new__() takes at least 24 arguments (25 given)
Yes, I followed types and lists you meant.

**Comment by jstavel** [comment]
So I have to end my work. See you later.

**Comment by Bystroushaak** [comment]
Hm. I will remove the defaults - it was early design decision, which doesn't look very smart now.

**Comment by jstavel** [comment]
GenerateContract works well.
but GenerateReview hm....

**Comment by Bystroushaak** [comment]
Okay. There is new version of the package, which *should* fix this bug.

**Comment by jstavel** [comment]
I have checked arguments against request.GenerateReview.
There are all values at the function call. Just one is missing. But which one?

 Module edeposit.content.amqp, line 640, in send
TypeError: __new__() takes exactly 27 arguments (26 given)
> /opt/edeposit/src/edeposit.content/edeposit/content/amqp.py(640)send()
-> internal_url = originalfile.absolute_url()

**Comment by Bystroushaak** [comment]
Do you use ``misto_vydani``?

**Comment by jstavel** [comment]
you are right. Wrong number of arguments. Thanks.
