### ISSUE TITLE
ascii codec can't decode

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#22]
AMQPError(headers={'exception_type': "<type 'exceptions.UnicodeDecodeError'>", 'exception': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 141, in onMessageReceived\n    uuid\n  File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/__init__.py", line 52, in reactToAMQPMessage\n    get_review(message)\n  File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/specialization.py", line 99, in get_review\n    content=review_struct.get_rst(),\n  File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/structures/requests.py", line 136, in get_rst\n    key = key.encode("utf-8")\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc4 in position 7: ordinal not in range(128)', 'exception_name': 'UnicodeDecodeError', 'UUID': '{"context_UID": "4a354a2f86e2454d992116e91296bdb4", "session_data": {"id": "2670_001.pdf"}}'}, exception='', payload="'ascii' codec can't decode byte 0xc4 in position 7: ordinal not in range(128)", exception_name='UnicodeDecodeError')

**Comment by Bystroushaak** [comment]
Well. Input data have to be in ``utf-8``. This may be error at your side, or it may also be error at my side, because I put there few .encode("utf-8").

I may try to release package without it, so we would test it. What do you think?

**Comment by Bystroushaak** [comment]
Okay, try it now. I've added some utf-8 magic.

**Comment by jstavel** [comment]
I have some problem with buildout at edeposit-test. So I am working at some other problem.

**Comment by Bystroushaak** [comment]
No problem, take your time.

**Comment by Bystroushaak** [comment]
Closed - based at your feedback from morning hangout.
