### ISSUE TITLE
internal url je dlouhe a preteka

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#23]
Jestli by slo je zkratit. (ie. nahradit nejakym popisem) a href dat do pdf.
Pokusim se prilozit obrazek ohlasovaciho listku.

**Comment by jstavel** [comment]
![image](https://cloud.githubusercontent.com/assets/2276410/5919234/23c724d2-a632-11e4-873f-3229b5d84d8c.png)

**Comment by Bystroushaak** [comment]
Určitě šlo, ale zase je zde problém s tím když to někdo tiskne, tak nebude schopný to přepsat z papíru.

**Comment by jstavel** [comment]
jj.

**Comment by Bystroushaak** [comment]
No tak nevím, mám to dělat, nebo ne? Osobně bych byl radši, kdyby bylo prostě zaručeno, že odkaz nebude delší jak určitý počet znaků.

**Comment by jstavel** [comment]
toto bych nechal na diskusi. Ja nezarucim jednoduchym zpusobem omezeni url.
mozna by tam slo dat v pripade dlouheho url mensi font.

**Comment by Bystroushaak** [comment]
Bohužel, menší font by nešel, to je jedno z omezení toho rst2pdf, že mi to nedovolí tam nacpat.

Mám pár návrhů:
- Dát link pod celý ten výpis, kde by nevadilo, že bude dlouhý.
- Použít zkracovač. Zde by asi bylo lepší používat náš vlastní zkracovač, než nějaký cizí.
- Vkládat místo odkazu QR kód.

**Comment by jstavel** [comment]
nejaky zkoracovac by slo udelat.
Muzeme to dat do rozsireni.
linka by byla ve stylu: /ebooks/fasdfadsfasdlfjasdfjasdlkjjljl
To by slo a nebylo by to moc drahe.

**Comment by Bystroushaak** [comment]
Jo, to by se mi líbilo, pro uživatele by to bylo taky lepší, aby nemusel opisovat tak moc textu. Jinak tohle budeš muset vyrobit ty, ale kdybys nechtěl, dokázal bych to napsat velmi rychle v [bottle.py](http://bottlepy.org/), i když by to muselo běžet jako samostatný server. Ale ten jsme stejně chtěli dělat pro ten REST.

**Comment by jstavel** [comment]
na to Tvoje bottle.py se tesim.

**Comment by jstavel** [comment]
viz jstavel/edeposit#96

**Comment by Bystroushaak** [comment]
Možná by se to dalo vyřešit vložením kusu kódu který tam přidá mezeru. Vyzkoušet v pondělí.
