### ISSUE TITLE
resources/header_logo.png is too wide for the frame, rescaling

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#24]
[WARNING] image.py:468 image /home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/resources/header_logo.png is too wide for the frame, rescaling

**Comment by Bystroushaak** [comment]
Tohle je v pohodě, jen to prostě provede konverzi za běhu do velikosti jaká mu vyhovuje.

**Comment by Bystroushaak** [comment]
Resp. přijde mi lepší, když to větší logo zmenšuje, než kdyby ho to zvětšovalo.

**Comment by jstavel** [comment]
jasan, stejne bys ho musel zmensit.
