### ISSUE TITLE
got an unexpected keyword argument 'jednajici'

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#27]
Pri vygenerovani nove smlouvy:
se objevi chyba:

<li>  Module edeposit.content.amqp, line 551, in send</li>

</ul><p>TypeError: __new__() got an unexpected keyword argument 'jednajici'
</p>
                    </div>

**Comment by Bystroushaak** [comment]
Viz [Changelog](https://github.com/edeposit/edeposit.amqp.pdfgen/blob/master/CHANGES.rst#031) a issue založená p. Zalejskou v pátek https://github.com/jstavel/edeposit/issues/101
